### ISSUE TITLE
Got Error with our configuration

### ISSUE THREAD

**Issue by ombre8** [acteru/reaper#4]
Traceback (most recent call last):
  File "/opt/reaper/reaper.py", line 69, in <module>
    r.get_upstream_packages()
  File "/opt/reaper/reaper.py", line 33, in get_upstream_packages
    s_cnf = Config()
  File "/opt/reaper/reaper.py", line 12, in __init__
    with open('config.yaml', 'r') as config_load:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

**Comment by acteru** [comment]
fixed
